# Generated by Django 5.2.13 on 2026-07-03 13:12

import django.db.models.deletion
import seeker_profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("governorate", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cvs/",
                        validators=[seeker_profiles.models.validate_cv_file],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("date_from", models.CharField(max_length=7)),
                ("date_to", models.CharField(blank=True, max_length=7, null=True)),
                ("current", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="seeker_profiles.seekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(max_length=150)),
                ("year", models.PositiveIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_entries",
                        to="seeker_profiles.seekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="seeker_profiles.seekerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "name")},
            },
        ),
    ]
