# Generated by Django 5.2.13 on 2026-07-04 11:44

import django.db.models.deletion
import seeker_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker_profiles", "0001_initial"),
        ("users", "0014_alter_company_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeker_profile",
                to="users.jobseeker",
            ),
        ),
        migrations.CreateModel(
            name="JobSeekerAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=seeker_profiles.models.generate_job_seeker_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="users.jobseeker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Seeker Auth Token",
                "verbose_name_plural": "Job Seeker Auth Tokens",
            },
        ),
    ]
