# Generated by Django 5.2.13 on 2026-07-05 15:20

import seeker_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker_profiles", "0002_alter_seekerprofile_user_jobseekerauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekerprofile",
            name="external_picture_url",
            field=models.URLField(
                blank=True,
                help_text="رابط صورة خارجي (متل صورة حساب Google)، يُستخدم فقط إذا ما في profile_picture مرفوعة يدوياً",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                validators=[seeker_profiles.models.validate_profile_picture],
            ),
        ),
    ]
