# Generated by Django 5.2.13 on 2026-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker_profiles", "0003_seekerprofile_external_picture_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekerprofile",
            name="external_picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
