# Generated by Django 5.2.13 on 2026-07-08 09:30

import seeker_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker_profiles", "0004_alter_seekerprofile_external_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekerprofile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cvs_upload_path",
                validators=[seeker_profiles.models.validate_cv_file],
            ),
        ),
    ]
