# Generated by Django 5.2.13 on 2026-07-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprofile",
            old_name="external_logo_url",
            new_name="external_picture_url",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="logo",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
