# Generated by Django 5.2.13 on 2026-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="paraphrase-multilingual-MiniLM-L12-v2", max_length=100
                    ),
                ),
                ("embedding_version", models.CharField(default="v1", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recommendation Settings",
                "verbose_name_plural": "Recommendation Settings",
            },
        ),
    ]
