# Generated by Django 5.2.13 on 2026-07-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.PositiveIntegerField(
                        help_text="id الإعلان الأصلي قبل الحذف"
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_deletions",
                        to="admin_dashboard.adminuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Deletion Log",
                "verbose_name_plural": "Job Deletion Logs",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
