# Generated by Django 6.0.6 on 2026-06-09 02:53

import django.db.models.deletion
import jobs.models.company_token
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_company_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(help_text='اسم التخصص بالعربية', max_length=150)),
                ('name_en', models.CharField(help_text='اسم التخصص بالإنجليزية', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=jobs.models.company_token.generate_company_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_auth_tokens', to='users.company')),
            ],
            options={
                'verbose_name': 'Company Auth Token',
                'verbose_name_plural': 'Company Auth Tokens',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('damascus', 'دمشق'), ('aleppo', 'حلب'), ('homs', 'حمص'), ('latakia', 'اللاذقية'), ('tartus', 'طرطوس'), ('hama', 'حماة'), ('deir_ezzor', 'دير الزور'), ('raqqa', 'الرقة'), ('suwayda', 'السويداء'), ('daraa', 'درعا'), ('idlib', 'إدلب'), ('hasakah', 'الحسكة'), ('quneitra', 'القنيطرة'), ('rural_damascus', 'ريف دمشق')], max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('internship', 'تدريب'), ('freelance', 'عمل حر')], max_length=20)),
                ('work_mode', models.CharField(choices=[('onsite', 'حضوري'), ('remote', 'عن بُعد'), ('hybrid', 'هجين')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('draft', 'مسودة')], default='draft', max_length=10)),
                ('expires_at', models.DateField(help_text='تاريخ انتهاء مدة الوظيفة — إجباري')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='users.company')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='jobs.specialization')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
