# Generated by Django 5.2.13 on 2026-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_seed_specializations"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="required_skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="المهارات المطلوبة للوظيفة - JSON array",
            ),
        ),
    ]
