# Generated by Django 5.2.13 on 2026-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_company_jobseeker_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("job_seeker", "Job Seeker"), ("company", "Company")],
                default="job_seeker",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
