# Generated by Django 5.2.13 on 2026-05-24 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                help_text="Company phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be like +963991234567",
                        regex="^\\+\\d{10,13}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="phone_number",
            field=models.CharField(
                help_text="Phone number for contact",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be like +963991234567",
                        regex="^\\+\\d{10,13}$",
                    )
                ],
            ),
        ),
    ]
