# Generated by Django 5.2.13 on 2026-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_company_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
