# Generated by Django 5.2.13 on 2026-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_company_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="user_type",
            field=models.CharField(
                choices=[("job_seeker", "Job Seeker"), ("company", "Company")],
                default="job_seeker",
                max_length=20,
            ),
        ),
    ]
