# Generated by Django 5.2.13 on 2026-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_emailverification_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("programming", "Programming"),
                    ("civil", "Civil"),
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("finance", "Finance"),
                    ("marketing", "Marketing"),
                    ("hospitality", "Hospitality"),
                    ("other", "Other"),
                ],
                help_text="Type of company industry",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="governorate",
            field=models.CharField(
                choices=[
                    ("damascus", "Damascus"),
                    ("rural_damascus", "Rural Damascus"),
                    ("aleppo", "Aleppo"),
                    ("homs", "Homs"),
                    ("hama", "Hama"),
                    ("latakia", "Latakia"),
                    ("tartus", "Tartus"),
                    ("deir_ezzor", "Deir Ezzor"),
                    ("raqqa", "Raqqa"),
                    ("hasakah", "Hasakah"),
                    ("daraa", "Daraa"),
                    ("suwayda", "Suwayda"),
                    ("quneitra", "Quneitra"),
                    ("idlib", "Idlib"),
                ],
                help_text="Company location (governorate)",
                max_length=50,
            ),
        ),
    ]
