# Generated by Django 5.2.13 on 2026-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_company_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="approval_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="rejection_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
