# Generated by Django 5.2.13 on 2026-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_company_approval_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseeker",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
