# Generated by Django 5.2.13 on 2026-06-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_jobseeker_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseeker",
            name="status",
        ),
    ]
