# Generated by Django 5.2.13 on 2026-06-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_jobseeker_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverification",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="request_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
