# Generated by Django 5.2.13 on 2026-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_emailverification_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending_admin_approval",
                max_length=30,
            ),
        ),
    ]
